2025-05-30 11:29:52,416 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:29:52,420 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:29:54,491 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:29:54,494 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:29:59,305 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:29:59,308 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:30:33,834 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 67, in get_controller
    return import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:30:33,837 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:31:07,086 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:31:07,089 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:31:42,376 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:31:42,379 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:33:10,088 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:33:10,091 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:34:20,507 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:34:20,510 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:35:05,363 ERROR frappe Could not take error snapshot: 'dict' object has no attribute 'extend'
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 86, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/error.py", line 61, in log_error
    error_log = frappe.get_doc(
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-30 11:35:05,366 ERROR frappe Failed to run after request hook
Site: imransite
Form Dict: {}
Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 198, in init_request
    for before_request_task in frappe.get_hooks("before_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/path_resolver.py", line 117, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 397, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 23, in get_response
    return handle_exception(e, endpoint, path, http_status_code)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/serve.py", line 37, in handle_exception
    return ErrorPage(exception=e).render()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/utils.py", line 534, in cache_html_decorator
    html = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
    self.init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
    super().init_context()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
    self.context.update(get_website_settings())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 172, in get_website_settings
    hooks = frappe.get_hooks()
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1590, in _load_app_hooks
    append_hook(hooks, key, value)
  File "/home/server-admin/frappe-next-pagenew/apps/frappe/frappe/__init__.py", line 1634, in append_hook
    target[key].extend(value)
AttributeError: 'dict' object has no attribute 'extend'
2025-05-31 08:12:00,300 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'query': 'i', 'cmd': 'frappe_new.frappe_new_title.doctype.todo_item.todo_item.search_items'}
2025-05-31 08:12:00,301 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'query': 'im', 'cmd': 'frappe_new.frappe_new_title.doctype.todo_item.todo_item.search_items'}
2025-05-31 08:12:00,490 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'query': 'imr', 'cmd': 'frappe_new.frappe_new_title.doctype.todo_item.todo_item.search_items'}
2025-05-31 08:16:31,384 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'query': 'i', 'cmd': 'frappe_new.frappe_new_title.doctype.todo_item.todo_item.search_items'}
2025-05-31 08:16:31,440 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'query': 'im', 'cmd': 'frappe_new.frappe_new_title.doctype.todo_item.todo_item.search_items'}
2025-05-31 08:16:31,575 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'query': 'imr', 'cmd': 'frappe_new.frappe_new_title.doctype.todo_item.todo_item.search_items'}
2025-06-02 14:22:06,603 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {}
2025-06-02 14:23:08,541 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'genre': 'Action', 'cmd': 'frappe.desk.query_report.run'}
2025-06-02 14:23:15,183 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'genre': 'Action', 'cmd': 'frappe.desk.query_report.run'}
2025-06-02 14:23:50,620 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'genre': 'Action', 'cmd': 'frappe.desk.query_report.run'}
2025-06-03 07:37:05,086 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'report_name': 'News Views Analytics', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-03 07:55:25,574 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'report_name': 'News Views Analytics', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-03 09:39:45,375 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'report_name': 'News Views Analytics', 'filters': '{"viewed_on":"2025-06-12"}', 'ignore_prepared_report': 'false', 'are_default_filters': 'false', 'cmd': 'frappe.desk.query_report.run'}
2025-06-03 09:39:45,380 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'report_name': 'News Views Analytics', 'filters': '{"viewed_on":"2025-06-12"}', 'ignore_prepared_report': 'false', 'are_default_filters': 'false', 'cmd': 'frappe.desk.query_report.run'}
2025-06-03 09:40:16,313 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'report_name': 'News Views Analytics', 'filters': '{"viewed_on":"2025-06-12"}', 'ignore_prepared_report': 'false', 'are_default_filters': 'false', 'cmd': 'frappe.desk.query_report.run'}
2025-06-03 09:40:16,507 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'report_name': 'News Views Analytics', 'filters': '{"viewed_on":"2025-06-12"}', 'ignore_prepared_report': 'false', 'are_default_filters': 'false', 'cmd': 'frappe.desk.query_report.run'}
2025-06-03 10:17:44,283 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'doc': '{"docstatus":0,"doctype":"Home Work","name":"new-home-work-bhwtsezhnx","__islocal":1,"__unsaved":1,"owner":"Administrator","subject":"Tamil","class":"(10th-A)","status":"In Progress","teacher_name":"K.Arun Kumar","description":"தலைப்பு: என் பள்ளி\\nவாக்கியங்கள்:\\nஎன் பள்ளி பெரியதும் அழகானதும் ஆகும்.\\nநான் என் பள்ளிக்குச் செல்வதை விரும்புகிறேன்.","created_at":"2025-06-03"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-06-03 10:18:19,207 ERROR frappe New Exception collected in error log
Site: imransite
Form Dict: {'doc': '{"docstatus":0,"doctype":"Home Work","name":"new-home-work-bhwtsezhnx","__islocal":1,"__unsaved":1,"owner":"Administrator","subject":"Tamil","class":"(10th-A)","status":"In Progress","teacher_name":"K.Arun Kumar","description":"தலைப்பு: என் பள்ளி\\nவாக்கியங்கள்:\\nஎன் பள்ளி பெரியதும் அழகானதும் ஆகும்.\\nநான் என் பள்ளிக்குச் செல்வதை விரும்புகிறேன்.","created_at":"2025-06-03"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
